#!/bin/bash
#
# See man ffmpeg for details or ffmpeg -h encoder=h264_nvenc

INPUT="$1"
OUTPUT="$2"


ffmpeg -y -hwaccel cuvid -benchmark \
           -vcodec h264_cuvid \
           -i "$INPUT" \
           -vcodec hevc_nvenc \
           -preset slow \
           -profile:v main10 \
           -tier high \
           -rc vbr_2pass \
           -rc-lookahead 120 \
           -temporal-aq 1 \
           -strict_gop 1 \
           -qmin 0 \
           -qmax 35 \
           -acodec copy \
           "$OUTPUT"
