#!/bin/bash

# Pipe a comma delimited list of PIDs to ps_mem

ps_mem -d -p "$(pgrep -d ',' -f "$1")"

## thoughts
## need to exclude this:
#echo "exclude this: $BASHPID"
# put query into BASH array

#query=($(pgrep -d ',' -f "$1"))

#echo "query is: ${query[@]}" 

#possible=($( echo "${query[@]}" | sed "s|,$BASHPID||" ))

#echo "possible is: $possible"
