#!/bin/bash

# Start xflux daemon on Linux (crontab)
# Note: FLUXZ_DAY_LAT, FLUXZ_DAY_LON, and FLUXZ (actual zip code) are in global scope (export from bash_profile).
#       Day is arbitrarily selected at a position approximately on the other side of the world, since xflux seems
#       to only work in `night' mode...

hour_now=`date +%H`
kcode=4000

while getopts k: opt; do
  case $opt in
    k)
      kcode="$OPTARG" ;
      ;;
    \?)
      echo "Err 1: Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

# ignore if xflux is already running
if pidof -x "xflux" >/dev/null; then
    echo "Err 2: xflux is already running."
    exit 2
elif [ $hour_now -ge 18 ] || [ $hour_now -le 6 ]; then
	xflux -z "$FLUXZ" -k $kcode
  	echo "Starting xflux in Night mode."
else
	xflux -l "$FLUXZ_DAY_LAT" -g "$FLUXZ_DAY_LON" -k $kcode
	echo "Starting xflux in Day mode."
fi
